/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public class EntityBaseEntityCall_AvatarBase : EntityCall
	{
		public EntityBaseEntityCall_AvatarBase() : base()
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void reqBackToMain(UInt16 arg1)
		{
			Bundle pBundle = newCall("reqBackToMain");
			if(pBundle == null)
				return;

			bundle.writeUint16(arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AvatarBase : EntityCall
	{
		public EntityCellEntityCall_AvatarBase() : base()
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void anYeYiYangSkill(UInt32 arg1)
		{
			Bundle pBundle = newCall("anYeYiYangSkill");
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			sendCall(null);
		}

		public void changeAnimState(string arg1)
		{
			Bundle pBundle = newCall("changeAnimState");
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

		public void gotoPosition(Vector3 arg1, float arg2, float arg3)
		{
			Bundle pBundle = newCall("gotoPosition");
			if(pBundle == null)
				return;

			bundle.writeVector3(arg1);
			bundle.writeFloat(arg2);
			bundle.writeFloat(arg3);
			sendCall(null);
		}

		public void jiaSuSkill()
		{
			Bundle pBundle = newCall("jiaSuSkill");
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void nanShangJiaNanSkill(Vector3 arg1, Byte arg2)
		{
			Bundle pBundle = newCall("nanShangJiaNanSkill");
			if(pBundle == null)
				return;

			bundle.writeVector3(arg1);
			bundle.writeUint8(arg2);
			sendCall(null);
		}

		public void reqArriveSuccess()
		{
			Bundle pBundle = newCall("reqArriveSuccess");
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void xiaCiYiDingSkill(UInt32 arg1)
		{
			Bundle pBundle = newCall("xiaCiYiDingSkill");
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			sendCall(null);
		}

	}
	}
