/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 0;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 1;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 2;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_Friend_list = new Property();
			pAccount_Friend_list.name = "Friend_list";
			pAccount_Friend_list.properUtype = 4;
			pAccount_Friend_list.properFlags = 32;
			pAccount_Friend_list.aliasID = 3;
			pAccount_Friend_list.defaultVal = EntityDef.id2datatypes[23].parseDefaultValStr("");
			pAccountModule.propertys["Friend_list"] = pAccount_Friend_list; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_Friend_list.aliasID] = pAccount_Friend_list;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(Friend_list / 4).");

			Property pAccount_Icon = new Property();
			pAccount_Icon.name = "Icon";
			pAccount_Icon.properUtype = 3;
			pAccount_Icon.properFlags = 32;
			pAccount_Icon.aliasID = 4;
			UInt16 Account_Icon_defval;
			UInt16.TryParse("", out Account_Icon_defval);
			pAccount_Icon.defaultVal = Account_Icon_defval;
			pAccountModule.propertys["Icon"] = pAccount_Icon; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_Icon.aliasID] = pAccount_Icon;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(Icon / 3).");

			Property pAccount_Level = new Property();
			pAccount_Level.name = "Level";
			pAccount_Level.properUtype = 2;
			pAccount_Level.properFlags = 32;
			pAccount_Level.aliasID = 5;
			Byte Account_Level_defval;
			Byte.TryParse("", out Account_Level_defval);
			pAccount_Level.defaultVal = Account_Level_defval;
			pAccountModule.propertys["Level"] = pAccount_Level; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_Level.aliasID] = pAccount_Level;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(Level / 2).");

			Property pAccount_Name = new Property();
			pAccount_Name.name = "Name";
			pAccount_Name.properUtype = 1;
			pAccount_Name.properFlags = 32;
			pAccount_Name.aliasID = 6;
			string Account_Name_defval = "";
			pAccount_Name.defaultVal = Account_Name_defval;
			pAccountModule.propertys["Name"] = pAccount_Name; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_Name.aliasID] = pAccount_Name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(Name / 1).");

			List<DATATYPE_BASE> pAccount_backToMain_args = new List<DATATYPE_BASE>();

			Method pAccount_backToMain = new Method();
			pAccount_backToMain.name = "backToMain";
			pAccount_backToMain.methodUtype = 26;
			pAccount_backToMain.aliasID = 0;
			pAccount_backToMain.args = pAccount_backToMain_args;

			pAccountModule.methods["backToMain"] = pAccount_backToMain; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_backToMain.aliasID] = pAccount_backToMain;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(backToMain / 26).");

			List<DATATYPE_BASE> pAccount_enterBattleSpace_args = new List<DATATYPE_BASE>();

			Method pAccount_enterBattleSpace = new Method();
			pAccount_enterBattleSpace.name = "enterBattleSpace";
			pAccount_enterBattleSpace.methodUtype = 25;
			pAccount_enterBattleSpace.aliasID = 1;
			pAccount_enterBattleSpace.args = pAccount_enterBattleSpace_args;

			pAccountModule.methods["enterBattleSpace"] = pAccount_enterBattleSpace; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_enterBattleSpace.aliasID] = pAccount_enterBattleSpace;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(enterBattleSpace / 25).");

			List<DATATYPE_BASE> pAccount_reqAddFriendMessage_args = new List<DATATYPE_BASE>();
			pAccount_reqAddFriendMessage_args.Add(EntityDef.id2datatypes[4]);
			pAccount_reqAddFriendMessage_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqAddFriendMessage = new Method();
			pAccount_reqAddFriendMessage.name = "reqAddFriendMessage";
			pAccount_reqAddFriendMessage.methodUtype = 18;
			pAccount_reqAddFriendMessage.aliasID = 2;
			pAccount_reqAddFriendMessage.args = pAccount_reqAddFriendMessage_args;

			pAccountModule.methods["reqAddFriendMessage"] = pAccount_reqAddFriendMessage; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_reqAddFriendMessage.aliasID] = pAccount_reqAddFriendMessage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAddFriendMessage / 18).");

			List<DATATYPE_BASE> pAccount_reqChangeNameCall_args = new List<DATATYPE_BASE>();
			pAccount_reqChangeNameCall_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqChangeNameCall = new Method();
			pAccount_reqChangeNameCall.name = "reqChangeNameCall";
			pAccount_reqChangeNameCall.methodUtype = 17;
			pAccount_reqChangeNameCall.aliasID = 3;
			pAccount_reqChangeNameCall.args = pAccount_reqChangeNameCall_args;

			pAccountModule.methods["reqChangeNameCall"] = pAccount_reqChangeNameCall; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_reqChangeNameCall.aliasID] = pAccount_reqChangeNameCall;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqChangeNameCall / 17).");

			List<DATATYPE_BASE> pAccount_reqEnterMatchRoomMessage_args = new List<DATATYPE_BASE>();
			pAccount_reqEnterMatchRoomMessage_args.Add(EntityDef.id2datatypes[4]);
			pAccount_reqEnterMatchRoomMessage_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqEnterMatchRoomMessage = new Method();
			pAccount_reqEnterMatchRoomMessage.name = "reqEnterMatchRoomMessage";
			pAccount_reqEnterMatchRoomMessage.methodUtype = 21;
			pAccount_reqEnterMatchRoomMessage.aliasID = 4;
			pAccount_reqEnterMatchRoomMessage.args = pAccount_reqEnterMatchRoomMessage_args;

			pAccountModule.methods["reqEnterMatchRoomMessage"] = pAccount_reqEnterMatchRoomMessage; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_reqEnterMatchRoomMessage.aliasID] = pAccount_reqEnterMatchRoomMessage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqEnterMatchRoomMessage / 21).");

			List<DATATYPE_BASE> pAccount_reqMessageCall_args = new List<DATATYPE_BASE>();
			pAccount_reqMessageCall_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqMessageCall = new Method();
			pAccount_reqMessageCall.name = "reqMessageCall";
			pAccount_reqMessageCall.methodUtype = 16;
			pAccount_reqMessageCall.aliasID = 5;
			pAccount_reqMessageCall.args = pAccount_reqMessageCall_args;

			pAccountModule.methods["reqMessageCall"] = pAccount_reqMessageCall; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_reqMessageCall.aliasID] = pAccount_reqMessageCall;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqMessageCall / 16).");

			List<DATATYPE_BASE> pAccount_reqShowMatching_args = new List<DATATYPE_BASE>();
			pAccount_reqShowMatching_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqShowMatching = new Method();
			pAccount_reqShowMatching.name = "reqShowMatching";
			pAccount_reqShowMatching.methodUtype = 24;
			pAccount_reqShowMatching.aliasID = 6;
			pAccount_reqShowMatching.args = pAccount_reqShowMatching_args;

			pAccountModule.methods["reqShowMatching"] = pAccount_reqShowMatching; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_reqShowMatching.aliasID] = pAccount_reqShowMatching;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqShowMatching / 24).");

			List<DATATYPE_BASE> pAccount_reqUpdateFriendChatting_args = new List<DATATYPE_BASE>();
			pAccount_reqUpdateFriendChatting_args.Add(EntityDef.id2datatypes[5]);
			pAccount_reqUpdateFriendChatting_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqUpdateFriendChatting = new Method();
			pAccount_reqUpdateFriendChatting.name = "reqUpdateFriendChatting";
			pAccount_reqUpdateFriendChatting.methodUtype = 20;
			pAccount_reqUpdateFriendChatting.aliasID = 7;
			pAccount_reqUpdateFriendChatting.args = pAccount_reqUpdateFriendChatting_args;

			pAccountModule.methods["reqUpdateFriendChatting"] = pAccount_reqUpdateFriendChatting; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_reqUpdateFriendChatting.aliasID] = pAccount_reqUpdateFriendChatting;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqUpdateFriendChatting / 20).");

			List<DATATYPE_BASE> pAccount_reqUpdateFriendListUI_args = new List<DATATYPE_BASE>();

			Method pAccount_reqUpdateFriendListUI = new Method();
			pAccount_reqUpdateFriendListUI.name = "reqUpdateFriendListUI";
			pAccount_reqUpdateFriendListUI.methodUtype = 19;
			pAccount_reqUpdateFriendListUI.aliasID = 8;
			pAccount_reqUpdateFriendListUI.args = pAccount_reqUpdateFriendListUI_args;

			pAccountModule.methods["reqUpdateFriendListUI"] = pAccount_reqUpdateFriendListUI; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_reqUpdateFriendListUI.aliasID] = pAccount_reqUpdateFriendListUI;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqUpdateFriendListUI / 19).");

			List<DATATYPE_BASE> pAccount_reqUpdateMatchRoomChatting_args = new List<DATATYPE_BASE>();
			pAccount_reqUpdateMatchRoomChatting_args.Add(EntityDef.id2datatypes[12]);
			pAccount_reqUpdateMatchRoomChatting_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqUpdateMatchRoomChatting = new Method();
			pAccount_reqUpdateMatchRoomChatting.name = "reqUpdateMatchRoomChatting";
			pAccount_reqUpdateMatchRoomChatting.methodUtype = 23;
			pAccount_reqUpdateMatchRoomChatting.aliasID = 9;
			pAccount_reqUpdateMatchRoomChatting.args = pAccount_reqUpdateMatchRoomChatting_args;

			pAccountModule.methods["reqUpdateMatchRoomChatting"] = pAccount_reqUpdateMatchRoomChatting; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_reqUpdateMatchRoomChatting.aliasID] = pAccount_reqUpdateMatchRoomChatting;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqUpdateMatchRoomChatting / 23).");

			List<DATATYPE_BASE> pAccount_reqUpdateMatchRoomUI_args = new List<DATATYPE_BASE>();
			pAccount_reqUpdateMatchRoomUI_args.Add(EntityDef.id2datatypes[23]);

			Method pAccount_reqUpdateMatchRoomUI = new Method();
			pAccount_reqUpdateMatchRoomUI.name = "reqUpdateMatchRoomUI";
			pAccount_reqUpdateMatchRoomUI.methodUtype = 22;
			pAccount_reqUpdateMatchRoomUI.aliasID = 10;
			pAccount_reqUpdateMatchRoomUI.args = pAccount_reqUpdateMatchRoomUI_args;

			pAccountModule.methods["reqUpdateMatchRoomUI"] = pAccount_reqUpdateMatchRoomUI; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_reqUpdateMatchRoomUI.aliasID] = pAccount_reqUpdateMatchRoomUI;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqUpdateMatchRoomUI / 22).");

			List<DATATYPE_BASE> pAccount_addFriend_args = new List<DATATYPE_BASE>();
			pAccount_addFriend_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_addFriend = new Method();
			pAccount_addFriend.name = "addFriend";
			pAccount_addFriend.methodUtype = 2;
			pAccount_addFriend.aliasID = -1;
			pAccount_addFriend.args = pAccount_addFriend_args;

			pAccountModule.methods["addFriend"] = pAccount_addFriend; 
			pAccountModule.base_methods["addFriend"] = pAccount_addFriend;

			pAccountModule.idbase_methods[pAccount_addFriend.methodUtype] = pAccount_addFriend;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(addFriend / 2).");

			List<DATATYPE_BASE> pAccount_delFriend_args = new List<DATATYPE_BASE>();
			pAccount_delFriend_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_delFriend = new Method();
			pAccount_delFriend.name = "delFriend";
			pAccount_delFriend.methodUtype = 3;
			pAccount_delFriend.aliasID = -1;
			pAccount_delFriend.args = pAccount_delFriend_args;

			pAccountModule.methods["delFriend"] = pAccount_delFriend; 
			pAccountModule.base_methods["delFriend"] = pAccount_delFriend;

			pAccountModule.idbase_methods[pAccount_delFriend.methodUtype] = pAccount_delFriend;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(delFriend / 3).");

			List<DATATYPE_BASE> pAccount_mainSceneLoaded_args = new List<DATATYPE_BASE>();

			Method pAccount_mainSceneLoaded = new Method();
			pAccount_mainSceneLoaded.name = "mainSceneLoaded";
			pAccount_mainSceneLoaded.methodUtype = 4;
			pAccount_mainSceneLoaded.aliasID = -1;
			pAccount_mainSceneLoaded.args = pAccount_mainSceneLoaded_args;

			pAccountModule.methods["mainSceneLoaded"] = pAccount_mainSceneLoaded; 
			pAccountModule.base_methods["mainSceneLoaded"] = pAccount_mainSceneLoaded;

			pAccountModule.idbase_methods[pAccount_mainSceneLoaded.methodUtype] = pAccount_mainSceneLoaded;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(mainSceneLoaded / 4).");

			List<DATATYPE_BASE> pAccount_reqAddFriendMessageCall_args = new List<DATATYPE_BASE>();
			pAccount_reqAddFriendMessageCall_args.Add(EntityDef.id2datatypes[4]);
			pAccount_reqAddFriendMessageCall_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqAddFriendMessageCall = new Method();
			pAccount_reqAddFriendMessageCall.name = "reqAddFriendMessageCall";
			pAccount_reqAddFriendMessageCall.methodUtype = 5;
			pAccount_reqAddFriendMessageCall.aliasID = -1;
			pAccount_reqAddFriendMessageCall.args = pAccount_reqAddFriendMessageCall_args;

			pAccountModule.methods["reqAddFriendMessageCall"] = pAccount_reqAddFriendMessageCall; 
			pAccountModule.base_methods["reqAddFriendMessageCall"] = pAccount_reqAddFriendMessageCall;

			pAccountModule.idbase_methods[pAccount_reqAddFriendMessageCall.methodUtype] = pAccount_reqAddFriendMessageCall;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAddFriendMessageCall / 5).");

			List<DATATYPE_BASE> pAccount_reqAddFriendToMatchRoom_args = new List<DATATYPE_BASE>();
			pAccount_reqAddFriendToMatchRoom_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_reqAddFriendToMatchRoom = new Method();
			pAccount_reqAddFriendToMatchRoom.name = "reqAddFriendToMatchRoom";
			pAccount_reqAddFriendToMatchRoom.methodUtype = 8;
			pAccount_reqAddFriendToMatchRoom.aliasID = -1;
			pAccount_reqAddFriendToMatchRoom.args = pAccount_reqAddFriendToMatchRoom_args;

			pAccountModule.methods["reqAddFriendToMatchRoom"] = pAccount_reqAddFriendToMatchRoom; 
			pAccountModule.base_methods["reqAddFriendToMatchRoom"] = pAccount_reqAddFriendToMatchRoom;

			pAccountModule.idbase_methods[pAccount_reqAddFriendToMatchRoom.methodUtype] = pAccount_reqAddFriendToMatchRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAddFriendToMatchRoom / 8).");

			List<DATATYPE_BASE> pAccount_reqChangeName_args = new List<DATATYPE_BASE>();
			pAccount_reqChangeName_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqChangeName = new Method();
			pAccount_reqChangeName.name = "reqChangeName";
			pAccount_reqChangeName.methodUtype = 1;
			pAccount_reqChangeName.aliasID = -1;
			pAccount_reqChangeName.args = pAccount_reqChangeName_args;

			pAccountModule.methods["reqChangeName"] = pAccount_reqChangeName; 
			pAccountModule.base_methods["reqChangeName"] = pAccount_reqChangeName;

			pAccountModule.idbase_methods[pAccount_reqChangeName.methodUtype] = pAccount_reqChangeName;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqChangeName / 1).");

			List<DATATYPE_BASE> pAccount_reqCreateMatchRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_reqCreateMatchRoom = new Method();
			pAccount_reqCreateMatchRoom.name = "reqCreateMatchRoom";
			pAccount_reqCreateMatchRoom.methodUtype = 7;
			pAccount_reqCreateMatchRoom.aliasID = -1;
			pAccount_reqCreateMatchRoom.args = pAccount_reqCreateMatchRoom_args;

			pAccountModule.methods["reqCreateMatchRoom"] = pAccount_reqCreateMatchRoom; 
			pAccountModule.base_methods["reqCreateMatchRoom"] = pAccount_reqCreateMatchRoom;

			pAccountModule.idbase_methods[pAccount_reqCreateMatchRoom.methodUtype] = pAccount_reqCreateMatchRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqCreateMatchRoom / 7).");

			List<DATATYPE_BASE> pAccount_reqDeleteMatchRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_reqDeleteMatchRoom = new Method();
			pAccount_reqDeleteMatchRoom.name = "reqDeleteMatchRoom";
			pAccount_reqDeleteMatchRoom.methodUtype = 11;
			pAccount_reqDeleteMatchRoom.aliasID = -1;
			pAccount_reqDeleteMatchRoom.args = pAccount_reqDeleteMatchRoom_args;

			pAccountModule.methods["reqDeleteMatchRoom"] = pAccount_reqDeleteMatchRoom; 
			pAccountModule.base_methods["reqDeleteMatchRoom"] = pAccount_reqDeleteMatchRoom;

			pAccountModule.idbase_methods[pAccount_reqDeleteMatchRoom.methodUtype] = pAccount_reqDeleteMatchRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqDeleteMatchRoom / 11).");

			List<DATATYPE_BASE> pAccount_reqEnterMatchRoom_args = new List<DATATYPE_BASE>();
			pAccount_reqEnterMatchRoom_args.Add(EntityDef.id2datatypes[4]);
			pAccount_reqEnterMatchRoom_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqEnterMatchRoom = new Method();
			pAccount_reqEnterMatchRoom.name = "reqEnterMatchRoom";
			pAccount_reqEnterMatchRoom.methodUtype = 9;
			pAccount_reqEnterMatchRoom.aliasID = -1;
			pAccount_reqEnterMatchRoom.args = pAccount_reqEnterMatchRoom_args;

			pAccountModule.methods["reqEnterMatchRoom"] = pAccount_reqEnterMatchRoom; 
			pAccountModule.base_methods["reqEnterMatchRoom"] = pAccount_reqEnterMatchRoom;

			pAccountModule.idbase_methods[pAccount_reqEnterMatchRoom.methodUtype] = pAccount_reqEnterMatchRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqEnterMatchRoom / 9).");

			List<DATATYPE_BASE> pAccount_reqExitMatchRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_reqExitMatchRoom = new Method();
			pAccount_reqExitMatchRoom.name = "reqExitMatchRoom";
			pAccount_reqExitMatchRoom.methodUtype = 10;
			pAccount_reqExitMatchRoom.aliasID = -1;
			pAccount_reqExitMatchRoom.args = pAccount_reqExitMatchRoom_args;

			pAccountModule.methods["reqExitMatchRoom"] = pAccount_reqExitMatchRoom; 
			pAccountModule.base_methods["reqExitMatchRoom"] = pAccount_reqExitMatchRoom;

			pAccountModule.idbase_methods[pAccount_reqExitMatchRoom.methodUtype] = pAccount_reqExitMatchRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqExitMatchRoom / 10).");

			List<DATATYPE_BASE> pAccount_reqGiveClientToAvatar_args = new List<DATATYPE_BASE>();

			Method pAccount_reqGiveClientToAvatar = new Method();
			pAccount_reqGiveClientToAvatar.name = "reqGiveClientToAvatar";
			pAccount_reqGiveClientToAvatar.methodUtype = 15;
			pAccount_reqGiveClientToAvatar.aliasID = -1;
			pAccount_reqGiveClientToAvatar.args = pAccount_reqGiveClientToAvatar_args;

			pAccountModule.methods["reqGiveClientToAvatar"] = pAccount_reqGiveClientToAvatar; 
			pAccountModule.base_methods["reqGiveClientToAvatar"] = pAccount_reqGiveClientToAvatar;

			pAccountModule.idbase_methods[pAccount_reqGiveClientToAvatar.methodUtype] = pAccount_reqGiveClientToAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqGiveClientToAvatar / 15).");

			List<DATATYPE_BASE> pAccount_reqStartMatch_args = new List<DATATYPE_BASE>();

			Method pAccount_reqStartMatch = new Method();
			pAccount_reqStartMatch.name = "reqStartMatch";
			pAccount_reqStartMatch.methodUtype = 13;
			pAccount_reqStartMatch.aliasID = -1;
			pAccount_reqStartMatch.args = pAccount_reqStartMatch_args;

			pAccountModule.methods["reqStartMatch"] = pAccount_reqStartMatch; 
			pAccountModule.base_methods["reqStartMatch"] = pAccount_reqStartMatch;

			pAccountModule.idbase_methods[pAccount_reqStartMatch.methodUtype] = pAccount_reqStartMatch;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqStartMatch / 13).");

			List<DATATYPE_BASE> pAccount_reqStopMatch_args = new List<DATATYPE_BASE>();

			Method pAccount_reqStopMatch = new Method();
			pAccount_reqStopMatch.name = "reqStopMatch";
			pAccount_reqStopMatch.methodUtype = 14;
			pAccount_reqStopMatch.aliasID = -1;
			pAccount_reqStopMatch.args = pAccount_reqStopMatch_args;

			pAccountModule.methods["reqStopMatch"] = pAccount_reqStopMatch; 
			pAccountModule.base_methods["reqStopMatch"] = pAccount_reqStopMatch;

			pAccountModule.idbase_methods[pAccount_reqStopMatch.methodUtype] = pAccount_reqStopMatch;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqStopMatch / 14).");

			List<DATATYPE_BASE> pAccount_sendChattingMessage_args = new List<DATATYPE_BASE>();
			pAccount_sendChattingMessage_args.Add(EntityDef.id2datatypes[5]);
			pAccount_sendChattingMessage_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_sendChattingMessage = new Method();
			pAccount_sendChattingMessage.name = "sendChattingMessage";
			pAccount_sendChattingMessage.methodUtype = 6;
			pAccount_sendChattingMessage.aliasID = -1;
			pAccount_sendChattingMessage.args = pAccount_sendChattingMessage_args;

			pAccountModule.methods["sendChattingMessage"] = pAccount_sendChattingMessage; 
			pAccountModule.base_methods["sendChattingMessage"] = pAccount_sendChattingMessage;

			pAccountModule.idbase_methods[pAccount_sendChattingMessage.methodUtype] = pAccount_sendChattingMessage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(sendChattingMessage / 6).");

			List<DATATYPE_BASE> pAccount_sendMessageToMatchRoom_args = new List<DATATYPE_BASE>();
			pAccount_sendMessageToMatchRoom_args.Add(EntityDef.id2datatypes[12]);
			pAccount_sendMessageToMatchRoom_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_sendMessageToMatchRoom = new Method();
			pAccount_sendMessageToMatchRoom.name = "sendMessageToMatchRoom";
			pAccount_sendMessageToMatchRoom.methodUtype = 12;
			pAccount_sendMessageToMatchRoom.aliasID = -1;
			pAccount_sendMessageToMatchRoom.args = pAccount_sendMessageToMatchRoom_args;

			pAccountModule.methods["sendMessageToMatchRoom"] = pAccount_sendMessageToMatchRoom; 
			pAccountModule.base_methods["sendMessageToMatchRoom"] = pAccount_sendMessageToMatchRoom;

			pAccountModule.idbase_methods[pAccount_sendMessageToMatchRoom.methodUtype] = pAccount_sendMessageToMatchRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(sendMessageToMatchRoom / 12).");

			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[4] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 0;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 1;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 2;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_anYeYiYangGold = new Property();
			pAvatar_anYeYiYangGold.name = "anYeYiYangGold";
			pAvatar_anYeYiYangGold.properUtype = 21;
			pAvatar_anYeYiYangGold.properFlags = 16;
			pAvatar_anYeYiYangGold.aliasID = 3;
			UInt16 Avatar_anYeYiYangGold_defval;
			UInt16.TryParse("2", out Avatar_anYeYiYangGold_defval);
			pAvatar_anYeYiYangGold.defaultVal = Avatar_anYeYiYangGold_defval;
			pAvatarModule.propertys["anYeYiYangGold"] = pAvatar_anYeYiYangGold; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_anYeYiYangGold.aliasID] = pAvatar_anYeYiYangGold;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(anYeYiYangGold / 21).");

			Property pAvatar_animState = new Property();
			pAvatar_animState.name = "animState";
			pAvatar_animState.properUtype = 18;
			pAvatar_animState.properFlags = 4;
			pAvatar_animState.aliasID = 4;
			string Avatar_animState_defval = "";
			pAvatar_animState.defaultVal = Avatar_animState_defval;
			pAvatarModule.propertys["animState"] = pAvatar_animState; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_animState.aliasID] = pAvatar_animState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(animState / 18).");

			Property pAvatar_goldNum = new Property();
			pAvatar_goldNum.name = "goldNum";
			pAvatar_goldNum.properUtype = 13;
			pAvatar_goldNum.properFlags = 16;
			pAvatar_goldNum.aliasID = 5;
			UInt16 Avatar_goldNum_defval;
			UInt16.TryParse("", out Avatar_goldNum_defval);
			pAvatar_goldNum.defaultVal = Avatar_goldNum_defval;
			pAvatarModule.propertys["goldNum"] = pAvatar_goldNum; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_goldNum.aliasID] = pAvatar_goldNum;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(goldNum / 13).");

			Property pAvatar_jiaSuGold = new Property();
			pAvatar_jiaSuGold.name = "jiaSuGold";
			pAvatar_jiaSuGold.properUtype = 20;
			pAvatar_jiaSuGold.properFlags = 16;
			pAvatar_jiaSuGold.aliasID = 6;
			UInt16 Avatar_jiaSuGold_defval;
			UInt16.TryParse("2", out Avatar_jiaSuGold_defval);
			pAvatar_jiaSuGold.defaultVal = Avatar_jiaSuGold_defval;
			pAvatarModule.propertys["jiaSuGold"] = pAvatar_jiaSuGold; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_jiaSuGold.aliasID] = pAvatar_jiaSuGold;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(jiaSuGold / 20).");

			Property pAvatar_keepJiaSuTime = new Property();
			pAvatar_keepJiaSuTime.name = "keepJiaSuTime";
			pAvatar_keepJiaSuTime.properUtype = 19;
			pAvatar_keepJiaSuTime.properFlags = 16;
			pAvatar_keepJiaSuTime.aliasID = 7;
			UInt16 Avatar_keepJiaSuTime_defval;
			UInt16.TryParse("1", out Avatar_keepJiaSuTime_defval);
			pAvatar_keepJiaSuTime.defaultVal = Avatar_keepJiaSuTime_defval;
			pAvatarModule.propertys["keepJiaSuTime"] = pAvatar_keepJiaSuTime; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_keepJiaSuTime.aliasID] = pAvatar_keepJiaSuTime;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(keepJiaSuTime / 19).");

			Property pAvatar_moveSpeed = new Property();
			pAvatar_moveSpeed.name = "moveSpeed";
			pAvatar_moveSpeed.properUtype = 14;
			pAvatar_moveSpeed.properFlags = 4;
			pAvatar_moveSpeed.aliasID = 8;
			float Avatar_moveSpeed_defval;
			float.TryParse("1", out Avatar_moveSpeed_defval);
			pAvatar_moveSpeed.defaultVal = Avatar_moveSpeed_defval;
			pAvatarModule.propertys["moveSpeed"] = pAvatar_moveSpeed; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_moveSpeed.aliasID] = pAvatar_moveSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(moveSpeed / 14).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 16;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 9;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 16).");

			Property pAvatar_nanShangJiaNanGold = new Property();
			pAvatar_nanShangJiaNanGold.name = "nanShangJiaNanGold";
			pAvatar_nanShangJiaNanGold.properUtype = 23;
			pAvatar_nanShangJiaNanGold.properFlags = 16;
			pAvatar_nanShangJiaNanGold.aliasID = 10;
			UInt16 Avatar_nanShangJiaNanGold_defval;
			UInt16.TryParse("2", out Avatar_nanShangJiaNanGold_defval);
			pAvatar_nanShangJiaNanGold.defaultVal = Avatar_nanShangJiaNanGold_defval;
			pAvatarModule.propertys["nanShangJiaNanGold"] = pAvatar_nanShangJiaNanGold; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_nanShangJiaNanGold.aliasID] = pAvatar_nanShangJiaNanGold;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(nanShangJiaNanGold / 23).");

			Property pAvatar_track = new Property();
			pAvatar_track.name = "track";
			pAvatar_track.properUtype = 12;
			pAvatar_track.properFlags = 4;
			pAvatar_track.aliasID = 11;
			Byte Avatar_track_defval;
			Byte.TryParse("", out Avatar_track_defval);
			pAvatar_track.defaultVal = Avatar_track_defval;
			pAvatarModule.propertys["track"] = pAvatar_track; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_track.aliasID] = pAvatar_track;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(track / 12).");

			Property pAvatar_xiaCiYiDingGold = new Property();
			pAvatar_xiaCiYiDingGold.name = "xiaCiYiDingGold";
			pAvatar_xiaCiYiDingGold.properUtype = 22;
			pAvatar_xiaCiYiDingGold.properFlags = 16;
			pAvatar_xiaCiYiDingGold.aliasID = 12;
			UInt16 Avatar_xiaCiYiDingGold_defval;
			UInt16.TryParse("2", out Avatar_xiaCiYiDingGold_defval);
			pAvatar_xiaCiYiDingGold.defaultVal = Avatar_xiaCiYiDingGold_defval;
			pAvatarModule.propertys["xiaCiYiDingGold"] = pAvatar_xiaCiYiDingGold; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_xiaCiYiDingGold.aliasID] = pAvatar_xiaCiYiDingGold;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(xiaCiYiDingGold / 22).");

			List<DATATYPE_BASE> pAvatar_ArriveDefeat_args = new List<DATATYPE_BASE>();
			pAvatar_ArriveDefeat_args.Add(EntityDef.id2datatypes[4]);

			Method pAvatar_ArriveDefeat = new Method();
			pAvatar_ArriveDefeat.name = "ArriveDefeat";
			pAvatar_ArriveDefeat.methodUtype = 34;
			pAvatar_ArriveDefeat.aliasID = 0;
			pAvatar_ArriveDefeat.args = pAvatar_ArriveDefeat_args;

			pAvatarModule.methods["ArriveDefeat"] = pAvatar_ArriveDefeat; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_ArriveDefeat.aliasID] = pAvatar_ArriveDefeat;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(ArriveDefeat / 34).");

			List<DATATYPE_BASE> pAvatar_ArriveSuccess_args = new List<DATATYPE_BASE>();

			Method pAvatar_ArriveSuccess = new Method();
			pAvatar_ArriveSuccess.name = "ArriveSuccess";
			pAvatar_ArriveSuccess.methodUtype = 33;
			pAvatar_ArriveSuccess.aliasID = 1;
			pAvatar_ArriveSuccess.args = pAvatar_ArriveSuccess_args;

			pAvatarModule.methods["ArriveSuccess"] = pAvatar_ArriveSuccess; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_ArriveSuccess.aliasID] = pAvatar_ArriveSuccess;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(ArriveSuccess / 33).");

			List<DATATYPE_BASE> pAvatar_jumpToPosition_args = new List<DATATYPE_BASE>();
			pAvatar_jumpToPosition_args.Add(EntityDef.id2datatypes[16]);

			Method pAvatar_jumpToPosition = new Method();
			pAvatar_jumpToPosition.name = "jumpToPosition";
			pAvatar_jumpToPosition.methodUtype = 36;
			pAvatar_jumpToPosition.aliasID = 2;
			pAvatar_jumpToPosition.args = pAvatar_jumpToPosition_args;

			pAvatarModule.methods["jumpToPosition"] = pAvatar_jumpToPosition; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_jumpToPosition.aliasID] = pAvatar_jumpToPosition;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(jumpToPosition / 36).");

			List<DATATYPE_BASE> pAvatar_startGameSecond_args = new List<DATATYPE_BASE>();
			pAvatar_startGameSecond_args.Add(EntityDef.id2datatypes[2]);

			Method pAvatar_startGameSecond = new Method();
			pAvatar_startGameSecond.name = "startGameSecond";
			pAvatar_startGameSecond.methodUtype = 32;
			pAvatar_startGameSecond.aliasID = 3;
			pAvatar_startGameSecond.args = pAvatar_startGameSecond_args;

			pAvatarModule.methods["startGameSecond"] = pAvatar_startGameSecond; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_startGameSecond.aliasID] = pAvatar_startGameSecond;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(startGameSecond / 32).");

			List<DATATYPE_BASE> pAvatar_reqBackToMain_args = new List<DATATYPE_BASE>();
			pAvatar_reqBackToMain_args.Add(EntityDef.id2datatypes[3]);

			Method pAvatar_reqBackToMain = new Method();
			pAvatar_reqBackToMain.name = "reqBackToMain";
			pAvatar_reqBackToMain.methodUtype = 31;
			pAvatar_reqBackToMain.aliasID = -1;
			pAvatar_reqBackToMain.args = pAvatar_reqBackToMain_args;

			pAvatarModule.methods["reqBackToMain"] = pAvatar_reqBackToMain; 
			pAvatarModule.base_methods["reqBackToMain"] = pAvatar_reqBackToMain;

			pAvatarModule.idbase_methods[pAvatar_reqBackToMain.methodUtype] = pAvatar_reqBackToMain;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqBackToMain / 31).");

			List<DATATYPE_BASE> pAvatar_anYeYiYangSkill_args = new List<DATATYPE_BASE>();
			pAvatar_anYeYiYangSkill_args.Add(EntityDef.id2datatypes[4]);

			Method pAvatar_anYeYiYangSkill = new Method();
			pAvatar_anYeYiYangSkill.name = "anYeYiYangSkill";
			pAvatar_anYeYiYangSkill.methodUtype = 39;
			pAvatar_anYeYiYangSkill.aliasID = -1;
			pAvatar_anYeYiYangSkill.args = pAvatar_anYeYiYangSkill_args;

			pAvatarModule.methods["anYeYiYangSkill"] = pAvatar_anYeYiYangSkill; 
			pAvatarModule.cell_methods["anYeYiYangSkill"] = pAvatar_anYeYiYangSkill;

			pAvatarModule.idcell_methods[pAvatar_anYeYiYangSkill.methodUtype] = pAvatar_anYeYiYangSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(anYeYiYangSkill / 39).");

			List<DATATYPE_BASE> pAvatar_changeAnimState_args = new List<DATATYPE_BASE>();
			pAvatar_changeAnimState_args.Add(EntityDef.id2datatypes[12]);

			Method pAvatar_changeAnimState = new Method();
			pAvatar_changeAnimState.name = "changeAnimState";
			pAvatar_changeAnimState.methodUtype = 37;
			pAvatar_changeAnimState.aliasID = -1;
			pAvatar_changeAnimState.args = pAvatar_changeAnimState_args;

			pAvatarModule.methods["changeAnimState"] = pAvatar_changeAnimState; 
			pAvatarModule.cell_methods["changeAnimState"] = pAvatar_changeAnimState;

			pAvatarModule.idcell_methods[pAvatar_changeAnimState.methodUtype] = pAvatar_changeAnimState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(changeAnimState / 37).");

			List<DATATYPE_BASE> pAvatar_gotoPosition_args = new List<DATATYPE_BASE>();
			pAvatar_gotoPosition_args.Add(EntityDef.id2datatypes[16]);
			pAvatar_gotoPosition_args.Add(EntityDef.id2datatypes[13]);
			pAvatar_gotoPosition_args.Add(EntityDef.id2datatypes[13]);

			Method pAvatar_gotoPosition = new Method();
			pAvatar_gotoPosition.name = "gotoPosition";
			pAvatar_gotoPosition.methodUtype = 35;
			pAvatar_gotoPosition.aliasID = -1;
			pAvatar_gotoPosition.args = pAvatar_gotoPosition_args;

			pAvatarModule.methods["gotoPosition"] = pAvatar_gotoPosition; 
			pAvatarModule.cell_methods["gotoPosition"] = pAvatar_gotoPosition;

			pAvatarModule.idcell_methods[pAvatar_gotoPosition.methodUtype] = pAvatar_gotoPosition;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(gotoPosition / 35).");

			List<DATATYPE_BASE> pAvatar_jiaSuSkill_args = new List<DATATYPE_BASE>();

			Method pAvatar_jiaSuSkill = new Method();
			pAvatar_jiaSuSkill.name = "jiaSuSkill";
			pAvatar_jiaSuSkill.methodUtype = 38;
			pAvatar_jiaSuSkill.aliasID = -1;
			pAvatar_jiaSuSkill.args = pAvatar_jiaSuSkill_args;

			pAvatarModule.methods["jiaSuSkill"] = pAvatar_jiaSuSkill; 
			pAvatarModule.cell_methods["jiaSuSkill"] = pAvatar_jiaSuSkill;

			pAvatarModule.idcell_methods[pAvatar_jiaSuSkill.methodUtype] = pAvatar_jiaSuSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(jiaSuSkill / 38).");

			List<DATATYPE_BASE> pAvatar_nanShangJiaNanSkill_args = new List<DATATYPE_BASE>();
			pAvatar_nanShangJiaNanSkill_args.Add(EntityDef.id2datatypes[16]);
			pAvatar_nanShangJiaNanSkill_args.Add(EntityDef.id2datatypes[2]);

			Method pAvatar_nanShangJiaNanSkill = new Method();
			pAvatar_nanShangJiaNanSkill.name = "nanShangJiaNanSkill";
			pAvatar_nanShangJiaNanSkill.methodUtype = 41;
			pAvatar_nanShangJiaNanSkill.aliasID = -1;
			pAvatar_nanShangJiaNanSkill.args = pAvatar_nanShangJiaNanSkill_args;

			pAvatarModule.methods["nanShangJiaNanSkill"] = pAvatar_nanShangJiaNanSkill; 
			pAvatarModule.cell_methods["nanShangJiaNanSkill"] = pAvatar_nanShangJiaNanSkill;

			pAvatarModule.idcell_methods[pAvatar_nanShangJiaNanSkill.methodUtype] = pAvatar_nanShangJiaNanSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(nanShangJiaNanSkill / 41).");

			List<DATATYPE_BASE> pAvatar_reqArriveSuccess_args = new List<DATATYPE_BASE>();

			Method pAvatar_reqArriveSuccess = new Method();
			pAvatar_reqArriveSuccess.name = "reqArriveSuccess";
			pAvatar_reqArriveSuccess.methodUtype = 30;
			pAvatar_reqArriveSuccess.aliasID = -1;
			pAvatar_reqArriveSuccess.args = pAvatar_reqArriveSuccess_args;

			pAvatarModule.methods["reqArriveSuccess"] = pAvatar_reqArriveSuccess; 
			pAvatarModule.cell_methods["reqArriveSuccess"] = pAvatar_reqArriveSuccess;

			pAvatarModule.idcell_methods[pAvatar_reqArriveSuccess.methodUtype] = pAvatar_reqArriveSuccess;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqArriveSuccess / 30).");

			List<DATATYPE_BASE> pAvatar_xiaCiYiDingSkill_args = new List<DATATYPE_BASE>();
			pAvatar_xiaCiYiDingSkill_args.Add(EntityDef.id2datatypes[4]);

			Method pAvatar_xiaCiYiDingSkill = new Method();
			pAvatar_xiaCiYiDingSkill.name = "xiaCiYiDingSkill";
			pAvatar_xiaCiYiDingSkill.methodUtype = 40;
			pAvatar_xiaCiYiDingSkill.aliasID = -1;
			pAvatar_xiaCiYiDingSkill.args = pAvatar_xiaCiYiDingSkill_args;

			pAvatarModule.methods["xiaCiYiDingSkill"] = pAvatar_xiaCiYiDingSkill; 
			pAvatarModule.cell_methods["xiaCiYiDingSkill"] = pAvatar_xiaCiYiDingSkill;

			pAvatarModule.idcell_methods[pAvatar_xiaCiYiDingSkill.methodUtype] = pAvatar_xiaCiYiDingSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(xiaCiYiDingSkill / 40).");

			ScriptModule pGoldModule = new ScriptModule("Gold");
			EntityDef.moduledefs["Gold"] = pGoldModule;
			EntityDef.idmoduledefs[5] = pGoldModule;

			Property pGold_position = new Property();
			pGold_position.name = "position";
			pGold_position.properUtype = 40000;
			pGold_position.properFlags = 4;
			pGold_position.aliasID = 0;
			Vector3 Gold_position_defval = new Vector3();
			pGold_position.defaultVal = Gold_position_defval;
			pGoldModule.propertys["position"] = pGold_position; 

			pGoldModule.usePropertyDescrAlias = true;
			pGoldModule.idpropertys[(UInt16)pGold_position.aliasID] = pGold_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gold), property(position / 40000).");

			Property pGold_direction = new Property();
			pGold_direction.name = "direction";
			pGold_direction.properUtype = 40001;
			pGold_direction.properFlags = 4;
			pGold_direction.aliasID = 1;
			Vector3 Gold_direction_defval = new Vector3();
			pGold_direction.defaultVal = Gold_direction_defval;
			pGoldModule.propertys["direction"] = pGold_direction; 

			pGoldModule.usePropertyDescrAlias = true;
			pGoldModule.idpropertys[(UInt16)pGold_direction.aliasID] = pGold_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gold), property(direction / 40001).");

			Property pGold_spaceID = new Property();
			pGold_spaceID.name = "spaceID";
			pGold_spaceID.properUtype = 40002;
			pGold_spaceID.properFlags = 16;
			pGold_spaceID.aliasID = 2;
			UInt32 Gold_spaceID_defval;
			UInt32.TryParse("", out Gold_spaceID_defval);
			pGold_spaceID.defaultVal = Gold_spaceID_defval;
			pGoldModule.propertys["spaceID"] = pGold_spaceID; 

			pGoldModule.usePropertyDescrAlias = true;
			pGoldModule.idpropertys[(UInt16)pGold_spaceID.aliasID] = pGold_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gold), property(spaceID / 40002).");

			Property pGold_goldValue = new Property();
			pGold_goldValue.name = "goldValue";
			pGold_goldValue.properUtype = 24;
			pGold_goldValue.properFlags = 4;
			pGold_goldValue.aliasID = 3;
			UInt16 Gold_goldValue_defval;
			UInt16.TryParse("", out Gold_goldValue_defval);
			pGold_goldValue.defaultVal = Gold_goldValue_defval;
			pGoldModule.propertys["goldValue"] = pGold_goldValue; 

			pGoldModule.usePropertyDescrAlias = true;
			pGoldModule.idpropertys[(UInt16)pGold_goldValue.aliasID] = pGold_goldValue;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gold), property(goldValue / 24).");

			Property pGold_name = new Property();
			pGold_name.name = "name";
			pGold_name.properUtype = 25;
			pGold_name.properFlags = 4;
			pGold_name.aliasID = 4;
			string Gold_name_defval = "";
			pGold_name.defaultVal = Gold_name_defval;
			pGoldModule.propertys["name"] = pGold_name; 

			pGoldModule.usePropertyDescrAlias = true;
			pGoldModule.idpropertys[(UInt16)pGold_name.aliasID] = pGold_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gold), property(name / 25).");

			pGoldModule.useMethodDescrAlias = true;
			ScriptModule pXiaCiYiDingPropModule = new ScriptModule("XiaCiYiDingProp");
			EntityDef.moduledefs["XiaCiYiDingProp"] = pXiaCiYiDingPropModule;
			EntityDef.idmoduledefs[6] = pXiaCiYiDingPropModule;

			Property pXiaCiYiDingProp_position = new Property();
			pXiaCiYiDingProp_position.name = "position";
			pXiaCiYiDingProp_position.properUtype = 40000;
			pXiaCiYiDingProp_position.properFlags = 4;
			pXiaCiYiDingProp_position.aliasID = 0;
			Vector3 XiaCiYiDingProp_position_defval = new Vector3();
			pXiaCiYiDingProp_position.defaultVal = XiaCiYiDingProp_position_defval;
			pXiaCiYiDingPropModule.propertys["position"] = pXiaCiYiDingProp_position; 

			pXiaCiYiDingPropModule.usePropertyDescrAlias = true;
			pXiaCiYiDingPropModule.idpropertys[(UInt16)pXiaCiYiDingProp_position.aliasID] = pXiaCiYiDingProp_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(XiaCiYiDingProp), property(position / 40000).");

			Property pXiaCiYiDingProp_direction = new Property();
			pXiaCiYiDingProp_direction.name = "direction";
			pXiaCiYiDingProp_direction.properUtype = 40001;
			pXiaCiYiDingProp_direction.properFlags = 4;
			pXiaCiYiDingProp_direction.aliasID = 1;
			Vector3 XiaCiYiDingProp_direction_defval = new Vector3();
			pXiaCiYiDingProp_direction.defaultVal = XiaCiYiDingProp_direction_defval;
			pXiaCiYiDingPropModule.propertys["direction"] = pXiaCiYiDingProp_direction; 

			pXiaCiYiDingPropModule.usePropertyDescrAlias = true;
			pXiaCiYiDingPropModule.idpropertys[(UInt16)pXiaCiYiDingProp_direction.aliasID] = pXiaCiYiDingProp_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(XiaCiYiDingProp), property(direction / 40001).");

			Property pXiaCiYiDingProp_spaceID = new Property();
			pXiaCiYiDingProp_spaceID.name = "spaceID";
			pXiaCiYiDingProp_spaceID.properUtype = 40002;
			pXiaCiYiDingProp_spaceID.properFlags = 16;
			pXiaCiYiDingProp_spaceID.aliasID = 2;
			UInt32 XiaCiYiDingProp_spaceID_defval;
			UInt32.TryParse("", out XiaCiYiDingProp_spaceID_defval);
			pXiaCiYiDingProp_spaceID.defaultVal = XiaCiYiDingProp_spaceID_defval;
			pXiaCiYiDingPropModule.propertys["spaceID"] = pXiaCiYiDingProp_spaceID; 

			pXiaCiYiDingPropModule.usePropertyDescrAlias = true;
			pXiaCiYiDingPropModule.idpropertys[(UInt16)pXiaCiYiDingProp_spaceID.aliasID] = pXiaCiYiDingProp_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(XiaCiYiDingProp), property(spaceID / 40002).");

			Property pXiaCiYiDingProp_acceptID = new Property();
			pXiaCiYiDingProp_acceptID.name = "acceptID";
			pXiaCiYiDingProp_acceptID.properUtype = 28;
			pXiaCiYiDingProp_acceptID.properFlags = 4;
			pXiaCiYiDingProp_acceptID.aliasID = 3;
			UInt32 XiaCiYiDingProp_acceptID_defval;
			UInt32.TryParse("", out XiaCiYiDingProp_acceptID_defval);
			pXiaCiYiDingProp_acceptID.defaultVal = XiaCiYiDingProp_acceptID_defval;
			pXiaCiYiDingPropModule.propertys["acceptID"] = pXiaCiYiDingProp_acceptID; 

			pXiaCiYiDingPropModule.usePropertyDescrAlias = true;
			pXiaCiYiDingPropModule.idpropertys[(UInt16)pXiaCiYiDingProp_acceptID.aliasID] = pXiaCiYiDingProp_acceptID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(XiaCiYiDingProp), property(acceptID / 28).");

			Property pXiaCiYiDingProp_launchID = new Property();
			pXiaCiYiDingProp_launchID.name = "launchID";
			pXiaCiYiDingProp_launchID.properUtype = 27;
			pXiaCiYiDingProp_launchID.properFlags = 4;
			pXiaCiYiDingProp_launchID.aliasID = 4;
			UInt32 XiaCiYiDingProp_launchID_defval;
			UInt32.TryParse("", out XiaCiYiDingProp_launchID_defval);
			pXiaCiYiDingProp_launchID.defaultVal = XiaCiYiDingProp_launchID_defval;
			pXiaCiYiDingPropModule.propertys["launchID"] = pXiaCiYiDingProp_launchID; 

			pXiaCiYiDingPropModule.usePropertyDescrAlias = true;
			pXiaCiYiDingPropModule.idpropertys[(UInt16)pXiaCiYiDingProp_launchID.aliasID] = pXiaCiYiDingProp_launchID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(XiaCiYiDingProp), property(launchID / 27).");

			Property pXiaCiYiDingProp_name = new Property();
			pXiaCiYiDingProp_name.name = "name";
			pXiaCiYiDingProp_name.properUtype = 30;
			pXiaCiYiDingProp_name.properFlags = 4;
			pXiaCiYiDingProp_name.aliasID = 5;
			string XiaCiYiDingProp_name_defval = "";
			pXiaCiYiDingProp_name.defaultVal = XiaCiYiDingProp_name_defval;
			pXiaCiYiDingPropModule.propertys["name"] = pXiaCiYiDingProp_name; 

			pXiaCiYiDingPropModule.usePropertyDescrAlias = true;
			pXiaCiYiDingPropModule.idpropertys[(UInt16)pXiaCiYiDingProp_name.aliasID] = pXiaCiYiDingProp_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(XiaCiYiDingProp), property(name / 30).");

			pXiaCiYiDingPropModule.useMethodDescrAlias = true;
			ScriptModule pNanShangJiaNanPropModule = new ScriptModule("NanShangJiaNanProp");
			EntityDef.moduledefs["NanShangJiaNanProp"] = pNanShangJiaNanPropModule;
			EntityDef.idmoduledefs[7] = pNanShangJiaNanPropModule;

			Property pNanShangJiaNanProp_position = new Property();
			pNanShangJiaNanProp_position.name = "position";
			pNanShangJiaNanProp_position.properUtype = 40000;
			pNanShangJiaNanProp_position.properFlags = 4;
			pNanShangJiaNanProp_position.aliasID = 0;
			Vector3 NanShangJiaNanProp_position_defval = new Vector3();
			pNanShangJiaNanProp_position.defaultVal = NanShangJiaNanProp_position_defval;
			pNanShangJiaNanPropModule.propertys["position"] = pNanShangJiaNanProp_position; 

			pNanShangJiaNanPropModule.usePropertyDescrAlias = true;
			pNanShangJiaNanPropModule.idpropertys[(UInt16)pNanShangJiaNanProp_position.aliasID] = pNanShangJiaNanProp_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NanShangJiaNanProp), property(position / 40000).");

			Property pNanShangJiaNanProp_direction = new Property();
			pNanShangJiaNanProp_direction.name = "direction";
			pNanShangJiaNanProp_direction.properUtype = 40001;
			pNanShangJiaNanProp_direction.properFlags = 4;
			pNanShangJiaNanProp_direction.aliasID = 1;
			Vector3 NanShangJiaNanProp_direction_defval = new Vector3();
			pNanShangJiaNanProp_direction.defaultVal = NanShangJiaNanProp_direction_defval;
			pNanShangJiaNanPropModule.propertys["direction"] = pNanShangJiaNanProp_direction; 

			pNanShangJiaNanPropModule.usePropertyDescrAlias = true;
			pNanShangJiaNanPropModule.idpropertys[(UInt16)pNanShangJiaNanProp_direction.aliasID] = pNanShangJiaNanProp_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NanShangJiaNanProp), property(direction / 40001).");

			Property pNanShangJiaNanProp_spaceID = new Property();
			pNanShangJiaNanProp_spaceID.name = "spaceID";
			pNanShangJiaNanProp_spaceID.properUtype = 40002;
			pNanShangJiaNanProp_spaceID.properFlags = 16;
			pNanShangJiaNanProp_spaceID.aliasID = 2;
			UInt32 NanShangJiaNanProp_spaceID_defval;
			UInt32.TryParse("", out NanShangJiaNanProp_spaceID_defval);
			pNanShangJiaNanProp_spaceID.defaultVal = NanShangJiaNanProp_spaceID_defval;
			pNanShangJiaNanPropModule.propertys["spaceID"] = pNanShangJiaNanProp_spaceID; 

			pNanShangJiaNanPropModule.usePropertyDescrAlias = true;
			pNanShangJiaNanPropModule.idpropertys[(UInt16)pNanShangJiaNanProp_spaceID.aliasID] = pNanShangJiaNanProp_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NanShangJiaNanProp), property(spaceID / 40002).");

			Property pNanShangJiaNanProp_launchID = new Property();
			pNanShangJiaNanProp_launchID.name = "launchID";
			pNanShangJiaNanProp_launchID.properUtype = 32;
			pNanShangJiaNanProp_launchID.properFlags = 4;
			pNanShangJiaNanProp_launchID.aliasID = 3;
			UInt32 NanShangJiaNanProp_launchID_defval;
			UInt32.TryParse("", out NanShangJiaNanProp_launchID_defval);
			pNanShangJiaNanProp_launchID.defaultVal = NanShangJiaNanProp_launchID_defval;
			pNanShangJiaNanPropModule.propertys["launchID"] = pNanShangJiaNanProp_launchID; 

			pNanShangJiaNanPropModule.usePropertyDescrAlias = true;
			pNanShangJiaNanPropModule.idpropertys[(UInt16)pNanShangJiaNanProp_launchID.aliasID] = pNanShangJiaNanProp_launchID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NanShangJiaNanProp), property(launchID / 32).");

			Property pNanShangJiaNanProp_name = new Property();
			pNanShangJiaNanProp_name.name = "name";
			pNanShangJiaNanProp_name.properUtype = 34;
			pNanShangJiaNanProp_name.properFlags = 4;
			pNanShangJiaNanProp_name.aliasID = 4;
			string NanShangJiaNanProp_name_defval = "";
			pNanShangJiaNanProp_name.defaultVal = NanShangJiaNanProp_name_defval;
			pNanShangJiaNanPropModule.propertys["name"] = pNanShangJiaNanProp_name; 

			pNanShangJiaNanPropModule.usePropertyDescrAlias = true;
			pNanShangJiaNanPropModule.idpropertys[(UInt16)pNanShangJiaNanProp_name.aliasID] = pNanShangJiaNanProp_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NanShangJiaNanProp), property(name / 34).");

			pNanShangJiaNanPropModule.useMethodDescrAlias = true;
		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "UINT8";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "BOOL";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "DBID";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "ENTITYID";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "INT32";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "VECTOR3";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "FRIEND_INFO";
				DATATYPE_FRIEND_INFO datatype = new DATATYPE_FRIEND_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "FRIEND_INFO_LIST";
				DATATYPE_FRIEND_INFO_LIST datatype = new DATATYPE_FRIEND_INFO_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "ENTITYCALL_LIST";
				DATATYPE_ENTITYCALL_LIST datatype = new DATATYPE_ENTITYCALL_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}