/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseEntityCall_AccountBase : EntityCall
	{
		public EntityBaseEntityCall_AccountBase() : base()
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void addFriend(string arg1)
		{
			Bundle pBundle = newCall("addFriend");
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

		public void delFriend(string arg1)
		{
			Bundle pBundle = newCall("delFriend");
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

		public void mainSceneLoaded()
		{
			Bundle pBundle = newCall("mainSceneLoaded");
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqAddFriendMessageCall(UInt32 arg1, string arg2)
		{
			Bundle pBundle = newCall("reqAddFriendMessageCall");
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void reqAddFriendToMatchRoom(UInt64 arg1)
		{
			Bundle pBundle = newCall("reqAddFriendToMatchRoom");
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void reqChangeName(string arg1)
		{
			Bundle pBundle = newCall("reqChangeName");
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

		public void reqCreateMatchRoom()
		{
			Bundle pBundle = newCall("reqCreateMatchRoom");
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqDeleteMatchRoom()
		{
			Bundle pBundle = newCall("reqDeleteMatchRoom");
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqEnterMatchRoom(UInt32 arg1, string arg2)
		{
			Bundle pBundle = newCall("reqEnterMatchRoom");
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void reqExitMatchRoom()
		{
			Bundle pBundle = newCall("reqExitMatchRoom");
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqGiveClientToAvatar()
		{
			Bundle pBundle = newCall("reqGiveClientToAvatar");
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqStartMatch()
		{
			Bundle pBundle = newCall("reqStartMatch");
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqStopMatch()
		{
			Bundle pBundle = newCall("reqStopMatch");
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void sendChattingMessage(UInt64 arg1, string arg2)
		{
			Bundle pBundle = newCall("sendChattingMessage");
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void sendMessageToMatchRoom(string arg1, string arg2)
		{
			Bundle pBundle = newCall("sendMessageToMatchRoom");
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AccountBase : EntityCall
	{
		public EntityCellEntityCall_AccountBase() : base()
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
