/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/NanShangJiaNanProp.def
	public class EntityBaseEntityCall_NanShangJiaNanPropBase : EntityCall
	{
		public EntityBaseEntityCall_NanShangJiaNanPropBase() : base()
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_NanShangJiaNanPropBase : EntityCall
	{
		public EntityCellEntityCall_NanShangJiaNanPropBase() : base()
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
