/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Gold : GoldBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Gold.def
	public abstract class GoldBase : Entity
	{
		public EntityBaseEntityCall_GoldBase baseEntityCall = null;
		public EntityCellEntityCall_GoldBase cellEntityCall = null;

		public UInt16 goldValue = 0;
		public virtual void onGoldValueChanged(UInt16 oldValue) {}
		public string name = "";
		public virtual void onNameChanged(string oldValue) {}


		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_GoldBase();
			baseEntityCall.id = id;
			baseEntityCall.className = className;
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_GoldBase();
			cellEntityCall.id = id;
			cellEntityCall.className = className;
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void onRemoteMethodCall(Method method, MemoryStream stream)
		{
			switch(method.methodUtype)
			{
				default:
					break;
			};
		}

		public override void onUpdatePropertys(Property prop, MemoryStream stream)
		{
			switch(prop.properUtype)
			{
				case 40001:
					Vector3 oldval_direction = direction;
					direction = stream.readVector3();

					if(prop.isBase())
					{
						if(inited)
							onDirectionChanged(oldval_direction);
					}
					else
					{
						if(inWorld)
							onDirectionChanged(oldval_direction);
					}

					break;
				case 24:
					UInt16 oldval_goldValue = goldValue;
					goldValue = stream.readUint16();

					if(prop.isBase())
					{
						if(inited)
							onGoldValueChanged(oldval_goldValue);
					}
					else
					{
						if(inWorld)
							onGoldValueChanged(oldval_goldValue);
					}

					break;
				case 25:
					string oldval_name = name;
					name = stream.readUnicode();

					if(prop.isBase())
					{
						if(inited)
							onNameChanged(oldval_name);
					}
					else
					{
						if(inWorld)
							onNameChanged(oldval_name);
					}

					break;
				case 40000:
					Vector3 oldval_position = position;
					position = stream.readVector3();

					if(prop.isBase())
					{
						if(inited)
							onPositionChanged(oldval_position);
					}
					else
					{
						if(inWorld)
							onPositionChanged(oldval_position);
					}

					break;
					case 40002:
						stream.readUint32();
						break;
				default:
					break;
			};
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs[className];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[1];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			UInt16 oldval_goldValue = goldValue;
			Property prop_goldValue = pdatas[3];
			if(prop_goldValue.isBase())
			{
				if(inited && !inWorld)
					onGoldValueChanged(oldval_goldValue);
			}
			else
			{
				if(inWorld)
				{
					if(prop_goldValue.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGoldValueChanged(oldval_goldValue);
					}
				}
			}

			string oldval_name = name;
			Property prop_name = pdatas[4];
			if(prop_name.isBase())
			{
				if(inited && !inWorld)
					onNameChanged(oldval_name);
			}
			else
			{
				if(inWorld)
				{
					if(prop_name.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameChanged(oldval_name);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[0];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

		}
	}
}